### ISSUE TITLE
Occasional Tapyrus-core crash in CI

### ISSUE THREAD

**Issue by Naviabheeman** [chaintope/tapyrus-core#254]
When feature_federation_management.py fails, tapyrusd seems to exit because of segmentation fault. The logs show that it happens when 'LoadExternalBlockFile: Out of order block ' condition is seen. 

```
[6472](https://github.com/Naviabheeman/tapyrus-core/actions/runs/4819591489/jobs/8583059635#step:3:6473) node3 2023-04-27T12:40:14.980717Z LoadExternalBlockFile: Out of order block 54f043779e0a6cd69c1391a03d6df82953209a97f3a066c9ea92d083ef00e018, parent ae265087d0683a7eac7cac9a8ec945dcadbb6d263267e855a0a848bd5b1c850b not known 
[6473](https://github.com/Naviabheeman/tapyrus-core/actions/runs/4819591489/jobs/8583059635#step:3:6474) node3 2023-04-27T12:40:14.980750Z LoadExternalBlockFile: Out of order block 01fa13b4ce7c3784607bf17bda84a5b9c1ad63c14889f2bece644d4386dabbe5, parent 54f043779e0a6cd69c1391a03d6df82953209a97f3a066c9ea92d083ef00e018not known 
[6474](https://github.com/Naviabheeman/tapyrus-core/actions/runs/4819591489/jobs/8583059635#step:3:6475) test 2023-04-27T12:40:15.753000Z TestFramework (ERROR): Unexpected exception caught during testing 
[6475](https://github.com/Naviabheeman/tapyrus-core/actions/runs/4819591489/jobs/8583059635#step:3:6476) 
[6476](https://github.com/Naviabheeman/tapyrus-core/actions/runs/4819591489/jobs/8583059635#step:3:6477)Traceback (most recent call last): 
[6477](https://github.com/Naviabheeman/tapyrus-core/actions/runs/4819591489/jobs/8583059635#step:3:6478) 
[6478](https://github.com/Naviabheeman/tapyrus-core/actions/runs/4819591489/jobs/8583059635#step:3:6479) File "/home/runner/work/tapyrus-core/tapyrus-core/build/tapyrus-core-x86_64-unknown-linux-gnu/test/functional/test_framework/test_framework.py", line 176, in main 
[6479](https://github.com/Naviabheeman/tapyrus-core/actions/runs/4819591489/jobs/8583059635#step:3:6480) 
[6480](https://github.com/Naviabheeman/tapyrus-core/actions/runs/4819591489/jobs/8583059635#step:3:6481) self.run_test() 
[6481](https://github.com/Naviabheeman/tapyrus-core/actions/runs/4819591489/jobs/8583059635#step:3:6482) 
[6482](https://github.com/Naviabheeman/tapyrus-core/actions/runs/4819591489/jobs/8583059635#step:3:6483) File "/home/runner/work/tapyrus-core/tapyrus-core/build/tapyrus-core-x86_64-unknown-linux-gnu/test/functional/feature_federation_management.py", line 648, in run_test 
[6483](https://github.com/Naviabheeman/tapyrus-core/actions/runs/4819591489/jobs/8583059635#step:3:6484) 
[6484](https://github.com/Naviabheeman/tapyrus-core/actions/runs/4819591489/jobs/8583059635#step:3:6485) self.start_node(3, ["-reloadxfield", "-loadblock=%s" % os.path.join(self.nodes[3].datadir, 'blk00000.dat')]) 
[6485](https://github.com/Naviabheeman/tapyrus-core/actions/runs/4819591489/jobs/8583059635#step:3:6486) 
[6486](https://github.com/Naviabheeman/tapyrus-core/actions/runs/4819591489/jobs/8583059635#step:3:6487) File "/home/runner/work/tapyrus-core/tapyrus-core/build/tapyrus-core-x86_64-unknown-linux-gnu/test/functional/test_framework/test_framework.py", line 302, in start_node 
[6487](https://github.com/Naviabheeman/tapyrus-core/actions/runs/4819591489/jobs/8583059635#step:3:6488) 
[6488](https://github.com/Naviabheeman/tapyrus-core/actions/runs/4819591489/jobs/8583059635#step:3:6489) elapsed = node.wait_for_rpc_connection() 
[6489](https://github.com/Naviabheeman/tapyrus-core/actions/runs/4819591489/jobs/8583059635#step:3:6490) 
[6490](https://github.com/Naviabheeman/tapyrus-core/actions/runs/4819591489/jobs/8583059635#step:3:6491) File "/home/runner/work/tapyrus-core/tapyrus-core/build/tapyrus-core-x86_64-unknown-linux-gnu/test/functional/test_framework/test_node.py", line 163, in wait_for_rpc_connection 
[6491](https://github.com/Naviabheeman/tapyrus-core/actions/runs/4819591489/jobs/8583059635#step:3:6492) 
[6492](https://github.com/Naviabheeman/tapyrus-core/actions/runs/4819591489/jobs/8583059635#step:3:6493) raise FailedToStartError(self._node_msg( 
[6493](https://github.com/Naviabheeman/tapyrus-core/actions/runs/4819591489/jobs/8583059635#step:3:6494)    
[6494](https://github.com/Naviabheeman/tapyrus-core/actions/runs/4819591489/jobs/8583059635#step:3:6495)test_framework.test_node.FailedToStartError: [node 3] tapyrusd exited with status -11 during initialization    
[6495](https://github.com/Naviabheeman/tapyrus-core/actions/runs/4819591489/jobs/8583059635#step:3:6496) test 2023-04-27T12:40:15.754000Z TestFramework (DEBUG): Closing down network thread    
[6496](https://github.com/Naviabheeman/tapyrus-core/actions/runs/4819591489/jobs/8583059635#step:3:6497) test 2023-04-27T12:40:15.804000Z TestFramework (INFO): Stopping nodes.  
```

Further investigation shows this:

```
[4812](https://github.com/Naviabheeman/tapyrus-core/actions/runs/4819591489/jobs/8583059635#step:3:4813) node3 2023-04-27T12:40:12.209655Z Blockpolicy estimates updated by 0 of 0 block txs, since last block 0 of 0 tracked, mempool map size 0, max target 0 from current 
[4813](https://github.com/Naviabheeman/tapyrus-core/actions/runs/4819591489/jobs/8583059635#step:3:4814) node3 2023-04-27T12:40:12.209674Z UpdateTip: new best=91fcebb61cace616d0c6459b5595a05cdb190e96dcde88c13ea1ae62bdfc1f54 height=21 version=0x00000001 tx=23 date='2023-04-27T12:40:00Z' progress=1.000000 cache=0.0MiB(23txo) 
[4814](https://github.com/Naviabheeman/tapyrus-core/actions/runs/4819591489/jobs/8583059635#step:3:4815) node3 2023-04-27T12:40:12.209690Z - Connect postprocess: 0.18ms [0.01s (0.28ms/blk)] 
[4815](https://github.com/Naviabheeman/tapyrus-core/actions/runs/4819591489/jobs/8583059635#step:3:4816) node3 2023-04-27T12:40:12.209699Z - Connect block: 0.35ms [0.01s (0.60ms/blk)] 
[4816](https://github.com/Naviabheeman/tapyrus-core/actions/runs/4819591489/jobs/8583059635#step:3:4817) node3 2023-04-27T12:40:12.209712Z Checking mempool with 0 transactions and 0 inputs 
[4817](https://github.com/Naviabheeman/tapyrus-core/actions/runs/4819591489/jobs/8583059635#step:3:4818) node3 2023-04-27T12:40:12.212428Z received: block (232 bytes) peer=1 
[4818](https://github.com/Naviabheeman/tapyrus-core/actions/runs/4819591489/jobs/8583059635#step:3:4819) node3 2023-04-27T12:40:12.212555Z received block 5367ffe459a289b57b9256e37df5d14198ee69955e8fd084920fd161b069fe0b peer=1 
[4819](https://github.com/Naviabheeman/tapyrus-core/actions/runs/4819591489/jobs/8583059635#step:3:4820) node3 2023-04-27T12:40:12.212667Z ERROR: ProcessNewBlock: AcceptBlock FAILED (bad-proof, Proof verification failed at height [37] (code 16))
```

When node3 is restarting, block height is just 26, newer blocks are being processed(height 37), which need to be validated with a different aggregate pub key. so block proof verification fails. but the block is stored on disk. Later on, when the node restarts, it is seen as an out of order block. This scenario is crashing tapyrusd.

**Comment by Naviabheeman** [comment]
This crash happens because a block is received during initial block download. 
_Node3_ is a new node in the network. It connects to the first peer - test framework and tries the initial block download. But the test framework node does not support initial block download. So _Node3_ ends IBD phase.
As a result other peer connections are accepted. The new nodes share headers and _Node3_ starts to download the blocks. But since it is an active peer, other nodes start sending it tip updates and block at the tip of the chain. _Node3_ receives, writes them to the disk, but keeps in a separate **out of order list** as the parent block is not known. 
The test involves federation pub key change. So proof verification fails for all newer blocks at the tip. This complicates the scenario further. Now there are out of order blocks which are invalid. 

The node is shutdown before it had the time to sync to the tip . So when it is later restarted with `-reloadxfield` its block file contains many out of order blocks which are invalid. _Node3_ cannot handle this scenario.

```
node3 2023-05-24T09:46:26.078093Z sending verack (0 bytes) peer=0 
[8741](https://github.com/chaintope/tapyrus-core/actions/runs/5066870490/jobs/9097207378#step:3:8742)
 node3 2023-05-24T09:46:26.078122Z receive version message: /Tapyrus Core:0.5.2(testnode1)/: version 10000, blocks=42, us=[::]:0, peer=0 
[8742](https://github.com/chaintope/tapyrus-core/actions/runs/5066870490/jobs/9097207378#step:3:8743)
 node3 2023-05-24T09:46:26.078136Z added time data, samples 2, offset +0 (+0 minutes) 
[8743](https://github.com/chaintope/tapyrus-core/actions/runs/5066870490/jobs/9097207378#step:3:8744)
 
[8758](https://github.com/chaintope/tapyrus-core/actions/runs/5066870490/jobs/9097207378#step:3:8759)
 node3 2023-05-24T09:46:26.106966Z received: verack (0 bytes) peer=0 
[8759](https://github.com/chaintope/tapyrus-core/actions/runs/5066870490/jobs/9097207378#step:3:8760)
 node3 2023-05-24T09:46:26.106996Z sending sendheaders (0 bytes) peer=0 
[8760](https://github.com/chaintope/tapyrus-core/actions/runs/5066870490/jobs/9097207378#step:3:8761)
 node3 2023-05-24T09:46:26.107041Z sending sendcmpct (9 bytes) peer=0 
[8761](https://github.com/chaintope/tapyrus-core/actions/runs/5066870490/jobs/9097207378#step:3:8762)
 node3 2023-05-24T09:46:26.107070Z sending sendcmpct (9 bytes) peer=0 
[8762](https://github.com/chaintope/tapyrus-core/actions/runs/5066870490/jobs/9097207378#step:3:8763)
 node3 2023-05-24T09:46:26.107112Z sending ping (8 bytes) peer=0 
[8763](https://github.com/chaintope/tapyrus-core/actions/runs/5066870490/jobs/9097207378#step:3:8764)
 node3 2023-05-24T09:46:26.107158Z Leaving InitialBlockDownload (latching to false)

**Comment by Naviabheeman** [comment]
Out of order blocks in the block files are the cause of this crash. I wan't able to simulate this scenario.

My initial doubt was that initial block download flag is not set when the new node tries to synch. This is not correct. I was able to simulate the new node, Node3 receiving a header whose aggregatepubkey is newer. i.e. Node3 is at height 9 before the federation block.  So it does not accept the new header.
```2023-06-08T13:34:43Z 0 addresses found from DNS seeds
2023-06-08T13:34:43Z dnsseed thread exit
2023-06-08T13:34:43Z msghand thread start
2023-06-08T13:34:43Z opencon thread start
2023-06-08T13:34:43Z init message: Done loading
2023-06-08T13:34:43Z addcon thread start
2023-06-08T13:34:44Z Leaving InitialBlockDownload (latching to false)
2023-06-08T13:34:44Z New outbound peer connected: version: 10000, blocks=141, peer=0
2023-06-08T13:35:02Z ERROR: AcceptBlockHeader: Consensus::CheckBlockHeader: 6a4020279f87db12d2e4ca03bc28277c2037e44dbf3922e28806a17bb19eff77, bad-proof, Proof verification failed at height [-1] (code 16)
2023-06-08T13:35:44Z Adding fixed seed nodes as DNS doesn't seem to be available.
2023-06-08T13:36:45Z ERROR: AcceptBlockHeader: Consensus::CheckBlockHeader: 6a4020279f87db12d2e4ca03bc28277c2037e44dbf3922e28806a17bb19eff77, bad-proof, Proof verification failed at height [-1] (code 16)
2023-06-08T13:36:47Z ERROR: AcceptBlockHeader: Consensus::CheckBlockHeader: 6a4020279f87db12d2e4ca03bc28277c2037e44dbf3922e28806a17bb19eff77, bad-proof, Proof verification failed at height [-1] (code 16)
```
This scenario does not write the block to the disk file and make it an out of synch block.

Initial block download status is also not to blame.
```
# ./tapyrus-cli -conf=/node3/tapyrus.conf  getblockchaininfo
{
...
  "blocks": 6,
  "headers": 23,
  "initialblockdownload": true,
  "aggregatePubkeys": [
    {
      "03e67ceb1f0af0ab4668227984782b48d286b88e54dc91487143199728d4597c02": 0
    } ],
...
}

# ./tapyrus-cli -conf=/node3/tapyrus.conf getblockchaininfo

{
...
  "blocks": 23,
  "headers": 23,
  "initialblockdownload": false,
  "aggregatePubkeys": [
    {
      "03e67ceb1f0af0ab4668227984782b48d286b88e54dc91487143199728d4597c02": 0
    },
    {
      "02b9a609d6bec0fdc9ba690986013cf7bbd13c54ffc25e6cf30916b4732c4a952a": 16
    }],
...
}
```

**Comment by Naviabheeman** [comment]
New logs from today's tests give us more information:

'''
node3 2023-07-03T17:03:23.722345Z Reindexing block file blk00000.dat... 
[18382](https://github.com/Naviabheeman/tapyrus-core/actions/runs/5446705578/jobs/9907823747#step:3:18383)
 node3 2023-07-03T17:03:23.724290Z LoadExternalBlockFile: nRewind : 0 (before out of order) 
[18383](https://github.com/Naviabheeman/tapyrus-core/actions/runs/5446705578/jobs/9907823747#step:3:18384)
 node3 2023-07-03T17:03:23.725349Z LoadExternalBlockFile: trying to read block **f32e14aeb72504603423d53095c67fe9a6633823c8df59b7727d7323b95c859a** 
[18384](https://github.com/Naviabheeman/tapyrus-core/actions/runs/5446705578/jobs/9907823747#step:3:18385)
 node3 2023-07-03T17:03:23.725391Z LoadExternalBlockFile: Read ok. nRewind = 345 
[18385](https://github.com/Naviabheeman/tapyrus-core/actions/runs/5446705578/jobs/9907823747#step:3:18386)
 node3 2023-07-03T17:03:23.725444Z LoadExternalBlockFile: before LookupBlockIndex 
[18386](https://github.com/Naviabheeman/tapyrus-core/actions/runs/5446705578/jobs/9907823747#step:3:18387)
 node3 2023-07-03T17:03:23.725471Z LoadExternalBlockFile: LookupBlockIndex returned null 
[18387](https://github.com/Naviabheeman/tapyrus-core/actions/runs/5446705578/jobs/9907823747#step:3:18388)
 node3 2023-07-03T17:03:23.725875Z   - Load block from disk: 0.36ms [0.00s] 
[18388](https://github.com/Naviabheeman/tapyrus-core/actions/runs/5446705578/jobs/9907823747#step:3:18389)
 node3 2023-07-03T17:03:23.726020Z   - Connect total: 0.15ms [0.00s (infms/blk)] 
[18389](https://github.com/Naviabheeman/tapyrus-core/actions/runs/5446705578/jobs/9907823747#step:3:18390)
 node3 2023-07-03T17:03:23.726036Z   - Flush: 0.02ms [0.00s (infms/blk)] 
[18390](https://github.com/Naviabheeman/tapyrus-core/actions/runs/5446705578/jobs/9907823747#step:3:18391)
 node3 2023-07-03T17:03:23.726055Z   - Writing chainstate: 0.02ms [0.00s (infms/blk)] 
[18391](https://github.com/Naviabheeman/tapyrus-core/actions/runs/5446705578/jobs/9907823747#step:3:18392)
 node3 2023-07-03T17:03:23.726081Z UpdateTip: new best=b67fdb6f4cea8b177fa0181f57dc4a57f042d1239b7b1ffc16e17ba70146c776 height=0 version=0x00000001 tx=1 date='2023-07-03T17:01:10Z' progress=1.000000 cache=0.0MiB(0txo) 
[18392](https://github.com/Naviabheeman/tapyrus-core/actions/runs/5446705578/jobs/9907823747#step:3:18393)
 node3 2023-07-03T17:03:23.726097Z   - Connect postprocess: 0.04ms [0.00s (infms/blk)] 
[18393](https://github.com/Naviabheeman/tapyrus-core/actions/runs/5446705578/jobs/9907823747#step:3:18394)
 node3 2023-07-03T17:03:23.726107Z - Connect block: 0.60ms [0.00s (infms/blk)] 
[18394](https://github.com/Naviabheeman/tapyrus-core/actions/runs/5446705578/jobs/9907823747#step:3:18395)
 node3 2023-07-03T17:03:23.726122Z Checking mempool with 0 transactions and 0 inputs 
[18395](https://github.com/Naviabheeman/tapyrus-core/actions/runs/5446705578/jobs/9907823747#step:3:18396)
 node3 2023-07-03T17:03:23.726169Z LoadExternalBlockFile: nRewind : 345 (before out of order) 
[18396](https://github.com/Naviabheeman/tapyrus-core/actions/runs/5446705578/jobs/9907823747#step:3:18397)
 node3 2023-07-03T17:03:23.726182Z LoadExternalBlockFile: trying to read block **f32e14aeb72504603423d53095c67fe9a6633823c8df59b7727d7323b95c859a** 
[18397](https://github.com/Naviabheeman/tapyrus-core/actions/runs/5446705578/jobs/9907823747#step:3:18398)
 node3 2023-07-03T17:03:23.726196Z LoadExternalBlockFile: Read ok. nRewind = 622 
[18398](https://github.com/Naviabheeman/tapyrus-core/actions/runs/5446705578/jobs/9907823747#step:3:18399)
 node3 2023-07-03T17:03:23.726208Z LoadExternalBlockFile: before LookupBlockIndex 
[18399](https://github.com/Naviabheeman/tapyrus-core/actions/runs/5446705578/jobs/9907823747#step:3:18400)
 node3 2023-07-03T17:03:23.726318Z LoadExternalBlockFile: nRewind : 622 (before out of order) 
[18400](https://github.com/Naviabheeman/tapyrus-core/actions/runs/5446705578/jobs/9907823747#step:3:18401)
 node3 2023-07-03T17:03:23.726500Z mapBlockIndex.size() = 2 
[18401](https://github.com/Naviabheeman/tapyrus-core/actions/runs/5446705578/jobs/9907823747#step:3:18402)
 node3 2023-07-03T17:03:23.726601Z LoadExternalBlockFile: trying to read block
'''

Here the block 'f32e14aeb72504603423d53095c67fe9a6633823c8df59b7727d7323b95c859a' is read successfully at first attempt. But the same block is tried again and again until the end of file is reached and the node crashes.

**Comment by Naviabheeman** [comment]
The source of this seems to be a special case in `ProcessHeadersMessage` to handle large reorg. Removing this code should fix the crash.

```
            // If pindexWalk still isn't on our main chain, we're looking at a
            // very large reorg at a time we think we're close to caught up to
            // the main chain -- this shouldn't really happen.  Bail out on the
            // direct fetch and rely on parallel download instead.
            if (!chainActive.Contains(pindexWalk)) {
                LogPrint(BCLog::NET, "Large reorg, won't direct fetch to %s (%d)\n",
                        pindexLast->GetBlockHash().ToString(),
                        pindexLast->nHeight);
            } else {
                std::vector<CInv> vGetData;
                // Download as much as possible, from earliest to latest.
                for (const CBlockIndex *pindex : reverse_iterate(vToFetch)) {
                    if (nodestate->nBlocksInFlight >= MAX_BLOCKS_IN_TRANSIT_PER_PEER) {
                        // Can't download any more from this peer
                        break;
                    }
                    vGetData.push_back(CInv(MSG_BLOCK, pindex->GetBlockHash()));
                    MarkBlockAsInFlight(pfrom->GetId(), pindex->GetBlockHash(), pindex);
                    LogPrint(BCLog::NET, "Requesting block %s from  peer=%d\n",
                            pindex->GetBlockHash().ToString(), pfrom->GetId());
                }
                if (vGetData.size() > 1) {
                    LogPrint(BCLog::NET, "Downloading blocks toward %s (%d) via headers direct fetch\n",
                            pindexLast->GetBlockHash().ToString(), pindexLast->nHeight);
                }
                if (vGetData.size() > 0) {
                    if (nodestate->fSupportsDesiredCmpctVersion && vGetData.size() == 1 && mapBlocksInFlight.size() == 1 && pindexLast->pprev->IsValid(BLOCK_VALID_CHAIN)) {
                        // In any case, we want to download using a compact block, not a regular one
                        vGetData[0] = CInv(MSG_CMPCT_BLOCK, vGetData[0].hash);
                    }
                    connman->PushMessage(pfrom, msgMaker.Make(NetMsgType::GETDATA, vGetData));
                }
            }
```


This code causes parallel fetch of two blocks at different heights. In the logs below we can see that it fetches blocks at height 22 and 42 at the same time.

 

```
 node3 2023-07-07T10:57:29.220454Z received: headers (7387 bytes) peer=0 
 node3 2023-07-07T10:57:29.224749Z Large reorg, won't direct fetch to 0a941906c9013536ab960876d1472d852ee68ba56e136016ab7bb9cfe9622862 (42) 

...
 node3 2023-07-07T10:57:29.305446Z Blockpolicy estimates updated by 0 of 0 block txs, since last block 0 of 0 tracked, mempool map size 0, max target 0 from current 
 node3 2023-07-07T10:57:29.305465Z UpdateTip: new best=3e58134fda596af8bdccf9fc727813253333e1bec3e58d6af444ca1d69eb1540 height=26 version=0x00000001 tx=32 date='2023-07-07T10:57:18Z' progress=1.000000 cache=0.0MiB(31txo) 
 node3 2023-07-07T10:57:29.305480Z   - Connect postprocess: 0.10ms [0.00s (0.15ms/blk)] 
 node3 2023-07-07T10:57:29.305501Z - Connect block: 0.64ms [0.02s (0.67ms/blk)] 
 node3 2023-07-07T10:57:29.305514Z Checking mempool with 0 transactions and 0 inputs 
 node3 2023-07-07T10:57:29.309110Z received: block (266 bytes) peer=1 
 node3 2023-07-07T10:57:29.309145Z received block 0a941906c9013536ab960876d1472d852ee68ba56e136016ab7bb9cfe9622862 peer=1 
 node3 2023-07-07T10:57:29.309255Z ERROR: ProcessNewBlock: AcceptBlock FAILED (bad-proof, Proof verification failed at height [42] (code 16)) 

```

**Comment by Naviabheeman** [comment]
I was able to re create this crash. locally using `p2p_sendheaders`. 


call stack:
```
std::__1::shared_ptr<CTransaction const>::get() const (/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1/__memory/shared_ptr.h:580)
CBlock::GetHeight() const (/Users/navia/Documents/Projects/Tapyrus/tapyrus-core-nb/236_DynamicBlockSigop/src/primitives/block.cpp:82)
LoadExternalBlockFile(__sFILE*, CDiskBlockPos*, CXFieldHistoryMap*) (/Users/navia/Documents/Projects/Tapyrus/tapyrus-core-nb/236_DynamicBlockSigop/src/validation.cpp:4265)
ThreadImport(std::__1::vector<boost::filesystem::path, std::__1::allocator<boost::filesystem::path>>, bool) (/Users/navia/Documents/Projects/Tapyrus/tapyrus-core-nb/236_DynamicBlockSigop/src/init.cpp:658)
decltype(static_cast<void (*&>(fp)(static_cast<std::__1::vector<boost::filesystem::path, std::__1::allocator<boost::filesystem::path>>&>(fp0), static_cast<bool&>(fp0))) std::__1::__invoke<void (*&)(std::__1::vector<boost::filesystem::path, std::__1::allocator<boost::filesystem::path>>, bool), std::__1::vector<boost::filesystem::path, std::__1::allocator<boost::filesystem::path>>&, bool&>(void (*&)(std::__1::vector<boost::filesystem::path, std::__1::allocator<boost::filesystem::path>>, bool), std::__1::vector<boost::filesystem::path, std::__1::allocator<boost::filesystem::path>>&, bool&) (/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1/type_traits:3918)
std::__1::__bind_return<void (*)(std::__1::vector<boost::filesystem::path, std::__1::allocator<boost::filesystem::path>>, bool), std::__1::tuple<std::__1::vector<boost::filesystem::path, std::__1::allocator<boost::filesystem::path>>, bool>, std::__1::tuple<>, __is_valid_bind_return<void (*)(std::__1::vector<boost::filesystem::path, std::__1::allocator<boost::filesystem::path>>, bool), std::__1::tuple<std::__1::vector<boost::filesystem::path, std::__1::allocator<boost::filesystem::path>>, bool>, std::__1::tuple<>>::value>::type std::__1::__apply_functor<void (*)(std::__1::vector<boost::filesystem::path, std::__1::allocator<boost::filesystem::path>>, bool), std::__1::tuple<std::__1::vector<boost::filesystem::path, std::__1::allocator<boost::filesystem::path>>, bool>, 0ul, 1ul, std::__1::tuple<>>(void (*&)(std::__1::vector<boost::filesystem::path, std::__1::allocator<boost::filesystem::path>>, bool), std::__1::tuple<std::__1::vector<boost::filesystem::path, std::__1::allocator<boost::filesystem::path>>, bool>&, std::__1::__tuple_indices<0ul, 1ul>, std::__1::tuple<>&&) (/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1/__functional/bind.h:257)
std::__1::__bind_return<void (*)(std::__1::vector<boost::filesystem::path, std::__1::allocator<boost::filesystem::path>>, bool), std::__1::tuple<std::__1::vector<boost::filesystem::path, std::__1::allocator<boost::filesystem::path>>, bool>, std::__1::tuple<>, __is_valid_bind_return<void (*)(std::__1::vector<boost::filesystem::path, std::__1::allocator<boost::filesystem::path>>, bool), std::__1::tuple<std::__1::vector<boost::filesystem::path, std::__1::allocator<boost::filesystem::path>>, bool>, std::__1::tuple<>>::value>::type std::__1::__bind<void (*)(std::__1::vector<boost::filesystem::path, std::__1::allocator<boost::filesystem::path>>, bool), std::__1::vector<boost::filesystem::path, std::__1::allocator<boost::filesystem::path>>&, bool&>::operator()<>() (/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1/__functional/bind.h:292)
decltype(static_cast<std::__1::__bind<void (*)(std::__1::vector<boost::filesystem::path, std::__1::allocator<boost::filesystem::path>>, bool), std::__1::vector<boost::filesystem::path, std::__1::allocator<boost::filesystem::path>>&, bool&>>(fp)()) std::__1::__invoke<std::__1::__bind<void (*)(std::__1::vector<boost::filesystem::path, std::__1::allocator<boost::filesystem::path>>, bool), std::__1::vector<boost::filesystem::path, std::__1::allocator<boost::filesystem::path>>&, bool&>>(std::__1::__bind<void (*)(std::__1::vector<boost::filesystem::path, std::__1::allocator<boost::filesystem::path>>, bool), std::__1::vector<boost::filesystem::path, std::__1::allocator<boost::filesystem::path>>&, bool&>&&) (/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1/type_traits:3918)
void std::__1::__thread_execute<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct>>, std::__1::__bind<void (*)(std::__1::vector<boost::filesystem::path, std::__1::allocator<boost::filesystem::path>>, bool), std::__1::vector<boost::filesystem::path, std::__1::allocator<boost::filesystem::path>>&, bool&>>(std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct>>, std::__1::__bind<void (*)(std::__1::vector<boost::filesystem::path, std::__1::allocator<boost::filesystem::path>>, bool), std::__1::vector<boost::filesystem::path, std::__1::allocator<boost::filesystem::path>>&, bool&>>&, std::__1::__tuple_indices<>) (/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1/thread:287)
void* std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct>>, std::__1::__bind<void (*)(std::__1::vector<boost::filesystem::path, std::__1::allocator<boost::filesystem::path>>, bool), std::__1::vector<boost::filesystem::path, std::__1::allocator<boost::filesystem::path>>&, bool&>>>(void*) (/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1/thread:298)
_pthread_start (@_pthread_start:32)
thread_start (@thread_start:8)
```

this bug was introduced in commit 58f3f4671164ca55d4f4993254a2494b2ed18436

**Comment by Naviabheeman** [comment]
This scenario can be re created locally using the new p2p_sendheaders test case. Remove the change made to "validation.cpp" in commit 09df78a and run the test. it would crash when restarted using "-reloadxfield" after mining the federation block.
