### ISSUE TITLE
Update ci container from ubuntu 20.04 to 22.04

### ISSUE THREAD

**Issue by azuchi** [chaintope/tapyrus-core#300]
Github Action workflows are currently running in Ubuntu 20.04 containers. EOL for Ubuntu 20.04 is April 2025. Therefore, upgrade all containers used in workflows to 22.04.

Currently, my local environment is 22.04 and I am able to build successfully.

**Comment by Naviabheeman** [comment]
You are right. The build completed successfully on ubuntu22.04. But there is a failure in functional test due to python version. 
```
stderr:
Traceback (most recent call last):
  File "/usr/lib/python3.10/hashlib.py", line 160, in __hash_new
    return _hashlib.new(name, data, **kwargs)
ValueError: [digital envelope routines] unsupported

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/runner/work/tapyrus-core/tapyrus-core/build/tapyrus-core-x86_64-unknown-linux-gnu/test/functional/feature_fee_estimation.py", line 28, in <module>
    P2SH_1 = CScript([OP_HASH160, hash160(REDEEM_SCRIPT_1), OP_EQUAL])
  File "/home/runner/work/tapyrus-core/tapyrus-core/build/tapyrus-core-x86_64-unknown-linux-gnu/test/functional/test_framework/script.py", line 25, in hash160
    return hashlib.new('ripemd160', sha256(s)).digest()
  File "/usr/lib/python3.10/hashlib.py", line 166, in __hash_new
    return __get_builtin_constructor(name)(data)
  File "/usr/lib/python3.10/hashlib.py", line 123, in __get_builtin_constructor
    raise ValueError('unsupported hash type ' + name)
ValueError: unsupported hash type ripemd160
```
I need to port ripemd160 implementation from bitcoin. But it looks like a minor change.

**Comment by azuchi** [comment]
Complete by #301
